# Generated by Django 5.0.4 on 2024-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('DateOfBirth', models.DateField(default='NULL')),
                ('Position', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
