# Generated by Django 5.0.4 on 2024-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Position',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
