# Generated by Django 5.0.4 on 2024-05-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfBirth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
