# Generated by Django 5.0.4 on 2024-05-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_employees_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('ExtraHours', models.IntegerField(default=0)),
                ('Forenoon', models.IntegerField(default=0)),
                ('Afternoon', models.IntegerField(default=0)),
                ('TotalHours', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employees')),
            ],
        ),
    ]
