# Generated by Django 5.0.4 on 2024-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_extrahours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='ExtraHours',
            field=models.IntegerField(default=0),
        ),
    ]
